[package]
name = "fera-fun"
version = "0.1.0"
authors = ["malbarbo"]
description = """
Free functions for fun programming.
"""
repository = "https://github.com/malbarbo/fera/tree/master/fun"
readme = "README.md"
license = "MPL-2.0"

[dev-dependencies]
version-sync = "0.9"
